### ISSUE TITLE
カテゴリがジャンルを考慮したモデルになっていない

### ISSUE THREAD

**Issue by jirokun** [jirokun/ReactiveRadarScope#2]
本来カテゴリをクリックすると、ジャンル画面に遷移する。
しかし、現状ではジャンルにIDが含まれたモデルになっていないため、どのカテゴリが
クリックされたのかの判定ができない状態。

ジャンルのモデルにIDを持たせ、その下位にあるジャンルを取得できるようなモデルに変更する必要がある。

**Comment by jirokun** [comment]
修正をmasterにマージしました。

**Comment by darker16** [comment]
> 本来カテゴリをクリックすると、ジャンル画面に遷移する。しかし、現状ではジャンルに画面に遷移する。しかし、現状ではジャンルにIDが含まいがため、どのカテゴリがクリックされたのかの判定ができない 状態 。
> 
> ジャンルのモデルにIDを持たせ、その下位にあるジャンルを取得できるようなモデルに変更快。
